### PR TITLE
update datasets with last version of haven (2.3.0)

### PR DESCRIPTION
**Pull request by larmarange**
With last stable version of `haven` (v2.3.0), `haven_labelled` class is now built with `vctrs`.

This PR updates *fertility* and *fecondite* with the last version of the classes.

### CODE REVIEW

**Comment by larmarange** [comment]
Just a quick comment: the update allows to preserve classes when merging datasets together.

**Comment by juba** [comment]
Merged, thanks !

**Comment by larmarange** [comment]
Thanks to you. I will release a new version of the labelled package today or tomorrow.

I do not know if you plan to release a new version of questionr. It would be great to release a minor version as these datasets are very useful when teaching how to deal with survey labelled data to students.

Best

**Comment by juba** [comment]
Sure ! Latest CRAN questionr version is quite old, more than a year ago...

I'll try to update it in the days to come. Would it be better for me to wait for the new `labelled` version to be on CRAN ?

**Comment by larmarange** [comment]
It could be better to be sure that all tests are OK when checking fro CRAN.
I just submitted to CRAN new version of labelled.

**Comment by juba** [comment]
Ok ! Let me know when the new version is online.

**Comment by larmarange** [comment]
It's done. New version of labelled (2.4.0) is on CRAN.

**Comment by juba** [comment]
Great ! questionr 0.7.1 is on its way, too.

**Comment by larmarange** [comment]
Thanks

**Pull request merged**
