### PR TITLE
describe + labelled functions + freq + ltabs

### PR DESCRIPTION
**Pull request by larmarange**

### CODE REVIEW

**Comment by juba** [comment]
Petite question concernant les fonctions autour des labels : est-ce qu'il y a une raison précise pour laquelle on recopie des fonctions du package `sjmisc` ? Est-ce que ça ne serait pas préférable de les importer ?

Désolé pour le délai, j'ai pris un peu de retard et j'essaie de passer en revue tout ça d'ici pas trop longtemps...

**Comment by briatte** [comment]
The author of `sjmisc` is working on the same kind of data as we are in the context of `questionr`. Some of his stuff is very similar to [what I coded for Stata](http://srqm.tumblr.com/post/44705634349/plotting-survey-data-a-wrapper-for-catplot) some time ago.

I would suggest either joining forces at some point, or aiming at 100% compatibility between `questionr` and `sjmisc` – `questionr` does the stats part, `sjmisc` does the plots part.

It's probably not possible to ensure 100% compatibility between `memisc` and `questionr` because Martin Elff has basically reinvented 90% of SPSS in R in his package, but perhaps it is possible to get there with `sjmisc` if the author likes the idea.

**Comment by larmarange** [comment]
My issue with `sjmisc` is that it contains a lot of extra staff not related to manipulation of labelled data. It's also provide its own version of `haven` import functions.

I totally agree that it would be better to have a package dedicated to labelled variables and shared between other packages.

In fact, I already asked Hadley if he would be interested for developing a package dedicated to manipulation of labelled variables (cf. https://github.com/hadley/haven/issues/83).

Hi answer was:

> I'm not interested in implementing such a package, but if someone else did, I'd be happy to use it in `haven`.

I have also contacted Daniel Lüdecke who developed `sjmisc` about the idea of extracting from `sjmisc` the functions dealing with labelled variables manipulation into a dedicated package focusing only on that question. cf. https://github.com/sjPlot/sjmisc/issues/7

He is OK with this idea. So I proposed to prepare a draft of such package. However it will require some time before to have something strong enough to be released on CRAN.

So, I see several options:

1. waiting for this package before to deal with labelled variable;
2. having a copy of some of these functions in questionr (eventually without exporting them) and, when the `labelled` package will be released, removing them and adding a dependency to the new package;
3. just suggesting `sjmisc` in `questionr` and using the `::` operator that allows to use some functions without importing them.

**Comment by larmarange** [comment]
Note: il faut aussi que je mettre à jour les messages avec `gettext()`.

Il y en encore du travail avant que cette pull request ne soit importable. ;-)

**Comment by briatte** [comment]
I completely understand Hadley Wickham is not interested. His work is on either lower level or higher level stuff.

It's great that you already contacted Daniel Lüdecke. My point was to say: let's make sure that no duplicated work gets done here.

**Comment by larmarange** [comment]
Ok. I will try to reorganise the code following option 3.

**Comment by larmarange** [comment]
I have created a new and cleaned pull request. cf. https://github.com/juba/questionr/pull/57

**Pull request closed without merging**
